selection_note.settings:
  type: config_object
  label: 'Settings'
  mapping:
    content_type:
      type: string
      label: 'Content type where to store notes'
    relation_type:
      type: string
      label: 'Relation type where to link relations'

node.type.*.third_party.selection_note:
  type: mapping
  label: 'Selection note per-node type third party settings.'
  mapping:
    field:
      type: string
      label: 'Field where to select text from for creating relations.'
